### PR TITLE
Update org-name in RabbitMQ examples

### PR DESCRIPTION
**Pull request by aashikam**
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/686

## Purpose
$title

### CODE REVIEW

**Comment by BuddhiWathsala** [comment]
Still failing the build with this error

```sh
error: runner/rabbitmq-transaction-consumer:0.1.0::rabbitmq_transaction_consumer.bal:15:5: Invalid resource signature for onMessage resource: The first parameter should be a rabbitmq:Message
```

https://github.com/ballerina-platform/ballerina-distribution/pull/688/checks?check_run_id=876166620

**Comment by aashikam** [comment]
> Still failing the build with this error
> 
> ```shell
> error: runner/rabbitmq-transaction-consumer:0.1.0::rabbitmq_transaction_consumer.bal:15:5: Invalid resource signature for onMessage resource: The first parameter should be a rabbitmq:Message
> ```
> 
> https://github.com/ballerina-platform/ballerina-distribution/pull/688/checks?check_run_id=876166620

https://github.com/ballerina-platform/ballerina-distribution/blob/94ecaa2b552f47609d2fa19a51ece5add1dad960/examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal#L15

It is `rabbitmq:Message`

**Comment by BuddhiWathsala** [comment]
> https://github.com/ballerina-platform/ballerina-distribution/blob/94ecaa2b552f47609d2fa19a51ece5add1dad960/examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal#L15
> 
> It is `rabbitmq:Message`.

I think so.

**Comment by aashikam** [comment]
> > https://github.com/ballerina-platform/ballerina-distribution/blob/94ecaa2b552f47609d2fa19a51ece5add1dad960/examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal#L15
> > 
> > It is `rabbitmq:Message`.
> 
> I think so.

Ah Okay I found the issue. This is coming from the compiler plugin. The `rabbitmq:Message` object is validated against `ballerina/rabbitmq:Message`. Will send the fix.

**Comment by aashikam** [comment]
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/8

**Pull request merged**
