### PR TITLE
Fix typo in "between" word (was "been").

### PR DESCRIPTION
**Pull request by kasabov**
> Resolves issue #2090

### CODE REVIEW

**Review by ThisaruGuruge — APPROVED** [review]

**Comment by ThisaruGuruge** [comment]
> [CLA assistant check](https://cla-assistant.io/ballerina-platform/ballerina-distribution?pullRequest=2091)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/ballerina-distribution?pullRequest=2091) before we can accept your contribution.
> 
> **Alex K** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/ballerina-distribution?pullRequest=2091) it.

Hi @kasabov 
Thank you for the PR. Can you please sign the user agreement?

**Comment by ThisaruGuruge** [comment]
Fixes #2090

**Comment by kasabov** [comment]
I thought I did. 

> You have agreed to the CLA for ballerina-platform/ballerina-distribution

Clicking the "recheck" button again doesn't help either. Does it generally just take longer or should I look into the part:

> Alex K seems not to be a GitHub user.

**Comment by ThisaruGuruge** [comment]
> I thought I did.
> 
> > You have agreed to the CLA for ballerina-platform/ballerina-distribution
> 
> Clicking the "recheck" button again doesn't help either. Does it generally just take longer or should I look into the part:
> 
> > Alex K seems not to be a GitHub user.

I guess the issue is that the email address of your GitHub account and the email address associated with the commit is different. You can add the email address associated with the commit, to your GitHub profile.

**Comment by kasabov** [comment]
That was it, @ThisaruGuruge. Sorry for the noise.

**Pull request merged**
