### PR TITLE
Update the "index.json" File with the BBE Permalinks

### PR DESCRIPTION
**Pull request by praneesha**
## Purpose
Update the "index.json" file with the BBE permalinks.

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by niveathika** [comment]
@praneesha Seems this is a constant across all bbes, cant we keep it somewhere common?

**Comment by praneesha** [comment]
> @praneesha Seems this is a constant across all bbes, cant we keep it somewhere common?

This is not a constant and will be different from one BBE to another.

**Review by keizer619 — APPROVED** [review]

**Comment by niveathika** [comment]
IMO, the permlink seems to be the url property of the bbe prefixed with "/learn/by-example/". Can't this be generated?

**Comment by keizer619** [comment]
> The permlink seems to be the url property of the bbe prefixed with "/learn/by-example/". IMO Can't this be generated?

@niveathika @praneesha 
If `/learn/by-example/` is a constant value and it will not be changed in future. We should be able to use `"/learn/by-example/" + sample.url` instead of `sample.permalink`

https://github.com/ballerina-platform/ballerina-dev-website/pull/2395/files#diff-896176a8651cb72a796a31654797aa291f4e9b9d3a43ed8adf43cb28e8bd1acaR25

**Comment by praneesha** [comment]
Closing since the fix above is added in https://github.com/ballerina-platform/ballerina-dev-website/pull/2395.

**Pull request closed without merging**
