### PR TITLE
Fix xmldata BBE output verification failure

### PR DESCRIPTION
**Pull request by kalaiyarasiganeshalingam**
## Purpose
$Subject

### CODE REVIEW

**Review by HindujaB — APPROVED** [review]

**Review by niveathika — COMMENTED** [review]
@kalaiyarasiganeshalingam Is this the correct fix? Shouldn't the versions be kept upto date rather than skipping the said logs?

**Comment by kalaiyarasiganeshalingam** [comment]
> Is this the correct fix? Shouldn't the versions be kept upto date rather than skipping the said logs?

Earlier, we faced the same issue in the 2201.0.x and fixed it with this fix.  
https://github.com/ballerina-platform/ballerina-distribution/pull/2823

**Comment by niveathika** [comment]
> Earlier, we faced the same issue in the 2201.0.x and fixed it with this fix.  
> https://github.com/ballerina-platform/ballerina-distribution/pull/2823

Wasnt it a special case? Where we did not want to pull the latest due to a bug in the GA pack?

**Comment by kalaiyarasiganeshalingam** [comment]
> > Earlier, we faced the same issue in the 2201.0.x and fixed it with this fix.
> > #2823
> 
> Wasnt that a special case? Where we did not want to pull the latest due to a bug in the GA pack?

Updated xmldata version in https://github.com/ballerina-platform/ballerina-distribution/pull/3755

**Pull request merged**
