### PR TITLE
Refactor names of the WebSocket BBEs

### PR DESCRIPTION
**Pull request by Bhashinee**
## Purpose
$subject.

### CODE REVIEW

**Comment by praneesha** [comment]
Shall we change the order as follows:

- Handle Text Messages with the Client
- Handle Text Messages with the Async Client
- Handle Binary Messages with the Client
- Handle Binary Message with the Async Client
- Listener Functionalities

@shafreenAnfar - Better if we can specify `the client` as `the default/primary/basic/sync client'. If not, shall we go with the above list?

**Comment by shafreenAnfar** [comment]
I am no expert. It is up to devrel team to decide. But I feel it is better without adding `the`.

**Comment by praneesha** [comment]
> I am no expert. It is up to devrel team to decide. But I feel it is better without adding `the`.

Need your feedback on the order change we did and if it is fine to specify the client as `the default/primary/basic/sync client`.

**Comment by praneesha** [comment]
LGTM now.

**Review by shafreenAnfar — APPROVED** [review]

**Pull request merged**
