### PR TITLE
Fix raw templates example

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes the raw template BBE

### CODE REVIEW

**Review by MaryamZi — APPROVED** [review]

**Comment by MaryamZi** [comment]
Need to enable the test(s) too?

**Comment by pubudu91** [comment]
> Need to enable the test(s) too?

There aren't any tests for this.

**Comment by MaryamZi** [comment]
> > Need to enable the test(s) too?
> 
> There aren't any tests for this.

Need to remove it from the ignore list https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina/build.gradle#L762.

**Comment by pubudu91** [comment]
> > > Need to enable the test(s) too?
> > 
> > 
> > There aren't any tests for this.
> 
> Need to remove it from the ignore list https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina/build.gradle#L762.

Ah missed this. Will send a PR

**Pull request merged**
